name: Github Action for NCP SSH
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: NCP SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      echo "Action runtime history: $(date)" >> ~/history.txt
                      cd ~/9room-frontend
                      git fetch --all
                      git reset --hard origin/main
                      npm install
                      npm run build
                      npm run start